#!/usr/bin/env bash

set -e

role=${CONTAINER_ROLE:-app}


if [ "$role" = "app" ]; then

    exec php-fpm

elif [ "$role" = "queue" ]; then

    echo "Queue role"
    php /var/www/yii queue/listen --verbose
    exit 1

elif [ "$role" = "scheduler" ]; then

    echo "Scheduler role"
    while [ true ]
    do
      php /var/www/yii schedule/run
      sleep 60
    done
    exit 1

else
    echo "Could not match the container role \"$role\""
    exit 1
fi